package project.OOP2.f22621615.enums;
public enum CommandEnum {
    OPEN, LOAD, CLOSE, SAVE, SAVEAS, HELP, EXIT, SHOWTABLES, DESCRIBE, PRINT, EXPORT,
    SELECT, ADDCOLUMN, UPDATE, DELETE, INSERT, RENAME, COUNT, AGGREGATE
}